### ISSUE TITLE
Store SPARQL queries

### ISSUE THREAD

**Issue by sebbader** [vocol/vocol#110]
The Querying tab should have a functionality to store, load, and update SPARQL queries. In addition, one could think about Unit Tests in order to ensure a certain level of quality when editing an ontology.

**Comment by lavdim** [comment]
Since the entire storing mechanism is based on Version Control, any file that the user push to the repository with .rq extension, will be automatically parsed and shown in the Querying Tab.

The idea of integrating Unit Tests is good, actually it is in our ToDo List.

**Comment by clange** [comment]
@lavdim good to know that .rq files are already supported. Where do they show up? Under "example queries", next to, e.g. "selection of classes"? If so, where is the title of the query taken from? Could you please 

1. point me to a VoCol project where such queries can already be seen, or
2. if there is no such project yet, add some queries to an existing project, so that we have something ready to demonstrate?

Also, one thing I'm not quite sure of is what data is being queried: just one file, or all RDF/OWL files in the repository? I.e., the ontology plus instance data?
