### ISSUE TITLE
Upgrading to VOWL 1.1.3

### ISSUE THREAD

**Issue by javadch** [vocol/vocol#117]
In WebVOWL 1.1.3 there are some useful features not available in VoCol: 
- [ ] in the bottom menu bar, one can select, create, or load an ontology from a URI. 
- [ ] In the "Mode" menu, one can enable the editing mode and start visually editing the ontology.
- [ ] It is possible to have more than one ontology registered in a single server, so that people can work on different ontologies. The URLs look like http://visualdataweb.de/webvowl/#ontoX

It would be great if you enable these features in VoCol too.

**Comment by lavdim** [comment]
Hello, this is actually a good features to have but: 

1. We intentionally disabled the option for loading/creating an ontology directly from WebVOWL interface integrated into VoCol. The complete change management should be done using the back-end based on Git.
2. Again, visually editing is not possible from the UI (not for now) because of conflict management and there is no API to load/save changes from WebVOWL to a Repository Hosting Platform, e.g. Github.
3. Collaborative Development is still not possible through WebVOWL. There are many features to be implemented in order to enable that, such as: rights management, lock-unlock mechanism, version management, conflict resolution, etc.

**Comment by javadch** [comment]
1. If I am not allowed to change anything through the UI how can ever work with VoCol? and then why I need GIT (if editing is not available)?
2. Is that VoCol (at least for now) is for viewing only?
3. Is there any way to edit/add/remove classes/properties using VoCol?

**Comment by lavdim** [comment]
The original idea of VoCol is to support ontology/vocabulary development on top of Version Control Systems. Currently, adding/removing/editing classes and properties can be done using "Editing" tab, i.e. a TurtleEditor, if the repository is hosted into Github. 

We are working in a new version of VoCol to allow hosting of multiple repositories containing ontologies into a single installation. In addition, in a long-term future, we aim to support the collaborative development based on pessimistic principles, i.e. lock-modify-unlock, which will enable editing from UI.
