### ISSUE TITLE
Vagrant box IP doesn't seem to be defaulting to 192.168.33.10

### ISSUE THREAD

**Issue by marijane** [vocol/vocol#67]
I followed the instructions to set up the vagrant box, except for the public URL  (see #66).  All my attempts to connect to 192.168.33.10 via http://192.168.33.10/docs/configuration_page.html or by pinging the IP are timing out.  

Other things to note:
- running "ip addr show" reveals a device at 10.0.2.15, but that address also times out.

What might be wrong?

**Comment by marijane** [comment]
Upon further investigation, it appears that the IP address and port forwarding settings are commented out in the Vagrantfile.  IP address works after uncommenting.

**Comment by lavdim** [comment]
Yes, the line should be uncommented, I will add to the installation instructions.

Related to the vagrant account, if you use public hosting platforms such as GitHub or BitBucket, there should be a way for these platforms to communicate with the running VoCol instance in order to deliver information about any change (push) event. In case that you do not have any URL and server which is publicly accessible then unfortunately this is the only way for the hosting platforms to communicate with VoCol instance. For the first time after configuration, VoCol with pull everything that you have in your repository and generate documentation, visualisation, etc., but after that there should a way to get notified for the push events.
Btw, there exists also a docker image of VoCol: https://hub.docker.com/r/lavdim/vocol/ , in case it is easier for you.
We are working to make VoCol as a service, where you can just subscribe your repository and benefit from all services, but for now I can not give any exact time.

**Comment by marijane** [comment]
Adding to the instructions is a good idea, because the Vagrantfile has a comment in it to the effect of not modifying it unless you know what you're doing!  I am more familiar with Vagrant than Docker, which is why I tried the Vagrant image first, but maybe I will try Docker next.

I do have a publicly accessible GitHub repository, and VoCol is pulling everything in, but it's failing to set up the web hook, which I believe is either due to the fact that the repo is owned by a GitHub organization I belong to, rather than my account, or the fact that my account has two-factor authentication turned on.

I did get it running last night, but lots of things are broken -- I get HTTP 500 errors trying to load the main home page or individual terms from the documentation, WebVOWL is asking to make sure PHP is turned on, and most of the analytics queries are not working.  I have yet to figure out why.

**Comment by lavdim** [comment]
The reason for getting HTTP errors and other, is that VoCol relies on the command-line pulling mechanism using user credentials. So if you use two-factor authentication, something that is not supported yet, VoCol will fail to pull the content from your repo, thus the rest of the tasks that are  automatically executed for documentation generation, visualization, etc. will fail as well. We will try to overcome this in the future. 

Since your repository if public, maybe you can send me the link so I can try and let you know about the result.

Ps. if you have access to the settings of the repository, you can manually create a web-hook that points to the VoCol instance by adding a */push* in the end of the url, e.g. *http://someurl.com/push* .

**Comment by marijane** [comment]
The link to my repository is https://github.com/OHSU-Library/ohsu-entities.

I am going to briefly disable 2FA on my account and do some experimentation myself.

**Comment by lavdim** [comment]
Added the explanations to the readme file for uncommenting the necessary line in Vagrant file.
